all:
  vars:
    ceph_fsid: "e2850e1f-7aab-472e-b6b1-824e19a75071"
    ceph_release: "quincy"
    ceph_network_public: "10.96.41.0/24"
    incus_name: "baremetal"
    ovn_name: "baremetal"
    incus_release: "stable"
    ovn_release: "ppa"
    ceph_prefix_disks: "/dev/disk/by-id/"
    ovs_bridge_name: "br-int"
    ovs_encap_type: "geneve"
    docker_daemon_config: {
      "iptables": false,
      "ip6tables": false,
      "bridge": "none",
      "log-level": "info",
      "live-restore": true,
      "storage-driver": "overlay2",
      "insecure-registries": [],
      "registry-mirrors": [],
      "dns": [],
      "dns-search": [],
      "exec-opts": [],
      "data-root": "/var/lib/docker"
    }
  children:
    baremetal:
      vars:
        ansible_connection: incus
        ansible_incus_remote: local
        ansible_user: root
        ansible_become: no
        ansible_incus_project: dev-incus-deploy
        ceph_roles:
          - client
          - osd
        incus_roles:
          - cluster
          - ui
        incus_init:
          network:
            LOCAL:
              type: macvlan
              local_config:
                parent: enp5s0
            # UPLINK:
              type: physical
              config:
                ipv4.gateway: "172.31.254.1/24"
                ipv6.gateway: "fd00:1e4d:637d:1234::1/64"
                ipv4.ovn.ranges: "172.31.254.10-172.31.254.254"
                dns.nameservers: "1.1.1.1,1.0.0.1"
              local_config:
                parent: enp6s0
            # default:
            #   type: ovn
            #   config:
            #     network: UPLINK
            #   default: true
          storage:
            local:
              driver: zfs
              local_config:
                source: "/dev/disk/by-id/nvme-QEMU_NVMe_Ctrl_incus_disk3"
            remote:
              driver: ceph
              local_config:
                source: "incus_{{ incus_name }}"
              default: true
        ovn_roles:
          - host
      hosts:
        server01:
          ceph_roles:
            - client
            - mon
            - mgr
            - osd
          ceph_disks:
            - data: nvme-QEMU_NVMe_Ctrl_incus_disk1
            - data: nvme-QEMU_NVMe_Ctrl_incus_disk2
          ovn_roles:
            - host
        server02:
          ceph_roles:
            - client
            - mon
            - mgr
            - osd
          ceph_disks:
            - data: nvme-QEMU_NVMe_Ctrl_incus_disk1
            - data: nvme-QEMU_NVMe_Ctrl_incus_disk2
          ovn_roles:
            - host
        server03:
          ceph_roles:
            - client
            - mon
            - mgr
            - osd
          ceph_disks:
            - data: nvme-QEMU_NVMe_Ctrl_incus_disk1
            - data: nvme-QEMU_NVMe_Ctrl_incus_disk2
          ovn_roles:
            - host

